#!/usr/bin/env node

const { version, name } = require('../package');
const { exec } = require('child_process');

let npmInfo = exec(`yarn info --json ${ name }`, (error, stdout) => {

  let npmVersion = JSON.parse(stdout)["data"]["version"];

  if (version === npmVersion) {
    process.stdout.write("No version change\n");
    process.exit(0);
  }

  process.stdout.write(`Publishing ${ name } to NPM\n`);

  // TODO: This doens't currently work because the user isn't logged in. This should be updated once
  // we find a way to programmatically log in the user.
  // https://github.com/yarnpkg/yarn/issues/3505
  exec(`yarn publish --new-version ${ version }`, (error, stdout) => {

    if (error) {
      process.stdout.write(`There was an error publishing ${ name } to NPM`);
      process.exit(1);
    }

    process.stdout.write(`Published ${ name } to NPM`);
  });
});
